// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

//forcing load .env from project root
dotenv.config({ path: path.resolve(__dirname, ".env") });
console.log("Loaded DATABASE_URL:", process.env.DATABASE_URL);

export default defineConfig({
  // schema: "prisma/schema.prisma",
  schema: "src/models",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
